// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCAd16RSDuaC-DOdei7Kfb2g94I9efcU',
    appId: '1:490102365408:web:46dcc9153d1890a2aa0485',
    messagingSenderId: '490102365408',
    projectId: 'pass-e0142',
    authDomain: 'pass-e0142.firebaseapp.com',
    storageBucket: 'pass-e0142.appspot.com',
    measurementId: 'G-YPWW2Y0ME9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoKHjWEJVivmFHY95agzUb7VBQBj_ggg8',
    appId: '1:490102365408:android:13c2e63cc4aa7853aa0485',
    messagingSenderId: '490102365408',
    projectId: 'pass-e0142',
    storageBucket: 'pass-e0142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0_TU0747l2_7KfEf-AC5ZWWVFIfufI4',
    appId: '1:490102365408:ios:a1da258813c9d46baa0485',
    messagingSenderId: '490102365408',
    projectId: 'pass-e0142',
    storageBucket: 'pass-e0142.appspot.com',
    iosBundleId: 'com.example.shadowpass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0_TU0747l2_7KfEf-AC5ZWWVFIfufI4',
    appId: '1:490102365408:ios:caf265bb648f78bcaa0485',
    messagingSenderId: '490102365408',
    projectId: 'pass-e0142',
    storageBucket: 'pass-e0142.appspot.com',
    iosBundleId: 'com.example.shadowpass.RunnerTests',
  );
}
